# Generated by Django 3.2.5 on 2021-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLayout', '0002_alter_herocard_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocard',
            name='alt',
        ),
        migrations.AddField(
            model_name='herocard',
            name='overview',
            field=models.CharField(default='Delivering Experiences That Students Love', max_length=150),
        ),
        migrations.AddField(
            model_name='herocard',
            name='title',
            field=models.CharField(default='Welcome to PeerToPeer learning', max_length=150),
        ),
    ]
