# Generated by Django 3.2.7 on 2022-02-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLayout', '0005_auto_20220215_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Section Title', max_length=100)),
                ('content', models.TextField(default='Section Content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentWithImagesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='app-layout/ContentWithImages/default.jpg', upload_to='app-layout/ContentWithImages/')),
                ('title', models.CharField(default='Section title', max_length=100)),
                ('content', models.CharField(default='Section subtitle', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_title', models.CharField(default='Config title', max_length=50)),
                ('section_one_title_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_one', to='AppLayout.contentsection')),
                ('section_two_title_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_two', to='AppLayout.contentsection')),
                ('section_with_images_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLayout.contentwithimagessection')),
            ],
        ),
    ]
