# Generated by Django 3.2.5 on 2021-08-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0002_auto_20210829_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='informatics_homework_slug',
        ),
    ]
