# Generated by Django 3.2.5 on 2021-08-29 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0002_auto_20210829_1959'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InformaticsDepartment', '0003_remove_homework_informatics_homework_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='InformaticsGroup',
        ),
        migrations.RenameModel(
            old_name='Homework',
            new_name='InformaticsHomework',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='InformaticsSchedule',
        ),
    ]
