# Generated by Django 3.2.5 on 2021-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0006_alter_informaticsschedule_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaticsschedule',
            name='deadline',
            field=models.DateField(),
        ),
    ]
