# Generated by Django 3.2.5 on 2021-09-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0008_alter_informaticsschedule_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informaticsschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='informaticsschedule',
            name='deadline',
        ),
    ]
