# Generated by Django 3.2.5 on 2021-09-12 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0009_auto_20210912_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticsschedule',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
