# Generated by Django 3.2.5 on 2021-09-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0010_informaticsschedule_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informaticsschedule',
            options={'ordering': ['deadline_date']},
        ),
        migrations.RenameField(
            model_name='informaticsschedule',
            old_name='deadline',
            new_name='deadline_date',
        ),
    ]
