# Generated by Django 3.2.5 on 2021-09-12 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0011_auto_20210912_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticsschedule',
            name='deadline_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
