# Generated by Django 3.2.5 on 2021-09-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0012_informaticsschedule_deadline_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaticsschedule',
            name='posted_on',
        ),
    ]
