# Generated by Django 3.2.5 on 2021-09-12 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0013_remove_informaticsschedule_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticsschedule',
            name='posted_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
