# Generated by Django 3.2.5 on 2021-09-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0014_informaticsschedule_posted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaticshomework',
            name='deadline',
        ),
    ]
