# Generated by Django 3.2.5 on 2021-09-12 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformaticsDepartment', '0015_remove_informaticshomework_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaticshomework',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='informaticshomework',
            name='deadline_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
