# Generated by Django 3.2.5 on 2021-09-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0002_auto_20210829_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
