# Generated by Django 3.2.5 on 2021-09-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0004_auto_20210917_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('message', models.TextField(default='')),
                ('target_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stats.teacher')),
            ],
        ),
    ]
