# Generated by Django 3.2.5 on 2021-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='', unique=True),
        ),
    ]
