# Generated by Django 3.2.7 on 2021-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0008_auto_20211008_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='scope',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='07 XXX XXX XX', max_length=100),
        ),
    ]
