# Generated by Django 3.2.7 on 2021-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0009_auto_20211017_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('log', models.TextField(default='', unique=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
