# Generated by Django 3.2.7 on 2021-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0012_teacherexpectation_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexpectation',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
