# Generated by Django 3.2.7 on 2021-10-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0013_teacherexpectation_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('log', models.TextField(default='', unique=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Stats.client')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
