# Generated by Django 3.2.7 on 2021-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0014_studentexpectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='07 XXX XXX XX', max_length=100),
        ),
    ]
