# Generated by Django 3.2.7 on 2021-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0015_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
