# Generated by Django 3.2.7 on 2021-11-30 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stats', '0016_alter_staff_email_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherExpectation',
            new_name='TeachersGoal',
        ),
    ]
