# Generated by Django 3.2.7 on 2021-11-30 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stats', '0017_rename_teacherexpectation_teachersgoal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachersGoal',
            new_name='TeacherGoal',
        ),
    ]
