# Generated by Django 3.2.7 on 2021-12-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_highschool'),
        ('Stats', '0018_rename_teachersgoal_teachergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='high_school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Details.highschool'),
        ),
    ]
