# Generated by Django 3.2.5 on 2021-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RomanianDepartment', '0002_auto_20210829_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='romanianhomework',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='romanianhomework',
            name='posted_on',
        ),
    ]
