# Generated by Django 3.2.5 on 2021-09-14 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomanianDepartment', '0003_auto_20210914_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='romanianhomework',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='romanianhomework',
            name='deadline_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='romanianhomework',
            name='posted_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
