# Generated by Django 3.2.5 on 2021-09-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RomanianDepartment', '0004_auto_20210914_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='romanianschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='romanianschedule',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='romanianschedule',
            name='posted_on',
        ),
    ]
