# Generated by Django 3.2.7 on 2021-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomanianDepartment', '0006_auto_20210914_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romaniangroup',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
