# Generated by Django 3.2.7 on 2022-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RomanianDepartment', '0007_alter_romaniangroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romanianhomework',
            name='file',
            field=models.FileField(blank=True, default='None', upload_to='homeworks/romanian'),
        ),
    ]
