# Generated by Django 3.2.5 on 2021-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(default='app-dependencies/hero-card-wallpaper/default.jpg', upload_to='app-dependencies/hero-card-wallpapers/')),
            ],
        ),
    ]
