# Generated by Django 3.2.7 on 2021-12-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDependencies', '0003_auto_20210905_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='Simple alt', max_length=100)),
                ('image', models.ImageField(default='app-dependencies/homework-card-wallpapers/default.jpg', upload_to='app-dependencies/homework-card-wallpapers/')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='Simple alt', max_length=100)),
                ('image', models.ImageField(default='app-dependencies/schedule-card-wallpapers/default.jpg', upload_to='app-dependencies/schedule-card-wallpapers/')),
            ],
        ),
    ]
