# Generated by Django 3.2.5 on 2021-08-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain',
            field=models.CharField(default='None', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='facultie',
            name='name',
            field=models.CharField(default='None', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='facultie',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Details.universitie'),
        ),
        migrations.AddField(
            model_name='highschoolprofile',
            name='profile',
            field=models.CharField(default='None', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(default='None', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='town',
            name='name',
            field=models.CharField(default='None', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='universitie',
            name='name',
            field=models.CharField(default='None', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='universitie',
            name='town',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Details.town'),
        ),
    ]
