# Generated by Django 3.2.7 on 2021-12-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_auto_20210829_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, unique=True)),
            ],
        ),
    ]
