# Generated by Django 3.2.5 on 2021-08-29 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0002_auto_20210829_1959'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MathematicsDepartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=15)),
                ('client', models.ManyToManyField(default=None, to='Stats.Client')),
                ('responsible_teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stats.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MathHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150, unique=True)),
                ('file', models.FileField(blank=True, default='None', upload_to='homeworks/informatics')),
                ('tips', models.TextField(blank=True, default='None')),
                ('optional', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
                ('dated', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(default=None, to='MathematicsDepartment.MathGroup')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MathSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default=None, max_length=100)),
                ('deadline', models.DateTimeField()),
                ('dated', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MathematicsDepartment.mathgroup')),
                ('teacher', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
