# Generated by Django 3.2.5 on 2021-09-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MathematicsDepartment', '0003_remove_mathhomework_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathhomework',
            name='posted_on',
        ),
    ]
