# Generated by Django 3.2.5 on 2021-09-14 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathematicsDepartment', '0004_remove_mathhomework_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathhomework',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mathhomework',
            name='deadline_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='mathhomework',
            name='posted_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
