# Generated by Django 3.2.5 on 2021-09-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MathematicsDepartment', '0005_auto_20210914_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='mathschedule',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='mathschedule',
            name='posted_on',
        ),
    ]
