# Generated by Django 3.2.5 on 2021-09-14 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathematicsDepartment', '0006_auto_20210914_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathschedule',
            options={'ordering': ['deadline_date']},
        ),
        migrations.AddField(
            model_name='mathschedule',
            name='deadline_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mathschedule',
            name='deadline_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='mathschedule',
            name='posted_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
