# Generated by Django 3.2.7 on 2022-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathematicsDepartment', '0008_alter_mathgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathhomework',
            name='file',
            field=models.FileField(blank=True, default='None', upload_to='homeworks/mathematics'),
        ),
    ]
